spring:
  application:
   name: AIRecommendationService

   data:
        mongodb:
            uri: mongodb://localhost:27017/airecommendation
            database: airecommendation
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

server:
   port: 8083
